### PR TITLE
Switches call for penalty kick

### PR DESCRIPTION
**Pull request by PatrickGoettsch**

### CODE REVIEW

**Comment by ahasselbring** [comment]
https://github.com/RoboCup-SPL/Rules/issues/43#issuecomment-1123378299

**Review by arnemoos — APPROVED** [review]

**Review by sseering — APPROVED** [review]
I think this is unabigous and correct for now so we should adopt it. However, I agree with Arne H.'s comment: we should/can simplify this in the future.

**Comment by ahasselbring** [comment]
But this is not how the GameController works.

**Comment by sseering** [comment]
Ok. I have undone my approval so we can discuss more later. Gotta stop for now.

**Comment by sseering** [comment]
I disliked 023acf0 because it

a) mixes "color" and "team".
b) still feels ambigous as discussed in https://github.com/RoboCup-SPL/Rules/issues/43 

I changed it to the version I would like. If you agree feel free to merge. If not feel free to revert.because it

a) mixes "color" and "team".
b) still feels ambigous as discussed in https://github.com/RoboCup-SPL/Rules/issues/43 

I changed it to the version I would like. If you agree feel free to merge. If not feel free to revert.

**Review by sseering — APPROVED** [review]

**Comment by PatrickGoettsch** [comment]
LGTM

**Pull request merged**
